"""Every schema, re-exported so call sites write `schemas.IngredientResponse`."""

from app.schemas.common_ingredient import (
    CommonIngredientResponse,
    CommonIngredientsIn,
)
from app.schemas.dish import DishCreate, DishResponse, DishSummary, DishUpdate
from app.schemas.heating import (
    HeatingNoteCreate,
    HeatingNoteResponse,
    HeatingNoteUpdate,
    HeatingOrderIn,
)
from app.schemas.image import (
    AttachedImage,
    CoverRef,
    ImageAttachmentIn,
    ImageDetail,
    ImageOwner,
    ImageSummary,
)
from app.schemas.ingredient import (
    HeatingIn,
    HeatingResponse,
    IngredientCreate,
    IngredientResponse,
    IngredientSummary,
    IngredientUpdate,
    LinkIn,
    LinkResponse,
    MergeIn,
    MergePreview,
    PreservationIn,
    PreservationResponse,
    RelatedIngredient,
    StorageRange,
)
from app.schemas.ingredient_category import (
    CategoryCreate,
    CategoryNode,
    CategoryResponse,
    CategoryUpdate,
)
from app.schemas.kitchen_note import (
    KitchenNoteCreate,
    KitchenNoteResponse,
    KitchenNoteSummary,
    KitchenNoteUpdate,
)
from app.schemas.label import LabelCreate, LabelResponse, LabelUpdate
from app.schemas.recipe import (
    DishBrief,
    DishRef,
    IngredientRef,
    LineGroupIn,
    LineGroupResponse,
    LineIn,
    LineResponse,
    NewDishIn,
    NewNameIn,
    NewSubDishIn,
    RecipeCreate,
    RecipeRef,
    RecipeResponse,
    RecipeSummary,
    RecipeUpdate,
    SourceIn,
    SourceResponse,
    StepGroupIn,
    StepGroupResponse,
    StepIn,
    StepResponse,
)
from app.schemas.recipe_template import (
    TemplateBody,
    TemplateBodyIn,
    TemplateCreate,
    TemplateFromRecipe,
    TemplateLine,
    TemplateLineGroup,
    TemplateOrderIn,
    TemplateResponse,
    TemplateStep,
    TemplateStepGroup,
    TemplateSummary,
    TemplateUpdate,
)
from app.schemas.schedule import (
    MealIn,
    MealItemIn,
    MealItemResponse,
    MealResponse,
    ScheduleDayIn,
    ScheduleDayResponse,
)
from app.schemas.tbd import (
    TbdEntryCreate,
    TbdEntryResponse,
    TbdEntryUpdate,
    TbdLinkIn,
    TbdLinkResponse,
    TbdOrderIn,
)
from app.schemas.vocabulary import (
    VocabRef,
    VocabularyCreate,
    VocabularyResponse,
    VocabularyUpdate,
)

# IngredientResponse names RecipeRef by a forward reference, because
# recipe.py imports ingredient.py; resolved here, once both are loaded.
IngredientResponse.model_rebuild(_types_namespace={"RecipeRef": RecipeRef})

__all__ = [
    "AttachedImage",
    "CommonIngredientResponse",
    "CommonIngredientsIn",
    "CoverRef",
    "DishBrief",
    "DishCreate",
    "DishRef",
    "DishResponse",
    "DishSummary",
    "DishUpdate",
    "HeatingNoteCreate",
    "HeatingNoteResponse",
    "HeatingNoteUpdate",
    "HeatingOrderIn",
    "ImageAttachmentIn",
    "ImageDetail",
    "ImageOwner",
    "ImageSummary",
    "HeatingIn",
    "HeatingResponse",
    "CategoryCreate",
    "CategoryNode",
    "CategoryResponse",
    "CategoryUpdate",
    "IngredientCreate",
    "IngredientRef",
    "IngredientResponse",
    "IngredientSummary",
    "IngredientUpdate",
    "KitchenNoteCreate",
    "KitchenNoteResponse",
    "KitchenNoteSummary",
    "KitchenNoteUpdate",
    "LabelCreate",
    "LabelResponse",
    "LabelUpdate",
    "LineGroupIn",
    "LineGroupResponse",
    "LineIn",
    "LineResponse",
    "LinkIn",
    "LinkResponse",
    "MealIn",
    "MealItemIn",
    "MealItemResponse",
    "MealResponse",
    "MergeIn",
    "MergePreview",
    "NewDishIn",
    "NewNameIn",
    "NewSubDishIn",
    "PreservationIn",
    "PreservationResponse",
    "RecipeCreate",
    "RecipeRef",
    "RecipeResponse",
    "RecipeSummary",
    "RecipeUpdate",
    "RelatedIngredient",
    "ScheduleDayIn",
    "ScheduleDayResponse",
    "SourceIn",
    "SourceResponse",
    "StepGroupIn",
    "StepGroupResponse",
    "StepIn",
    "StepResponse",
    "StorageRange",
    "TbdEntryCreate",
    "TbdEntryResponse",
    "TbdEntryUpdate",
    "TbdLinkIn",
    "TbdLinkResponse",
    "TbdOrderIn",
    "TemplateBody",
    "TemplateBodyIn",
    "TemplateCreate",
    "TemplateFromRecipe",
    "TemplateLine",
    "TemplateLineGroup",
    "TemplateOrderIn",
    "TemplateResponse",
    "TemplateStep",
    "TemplateStepGroup",
    "TemplateSummary",
    "TemplateUpdate",
    "VocabRef",
    "VocabularyCreate",
    "VocabularyResponse",
    "VocabularyUpdate",
]
